### Find All Runs
GET http://localhost:8080/api/runs

### Find Run By ID
GET http://localhost:8080/api/runs/1

### Find Run By ID
GET http://localhost:8080/api/runs/99

### Create new Run
POST http://localhost:8080/api/runs
Content-Type: RunnerzApplication/json

{
  "id": 10,
  "title": "Saturday Morning Run",
  "startedOn": "2024-02-10T15:00:12.49766",
  "completedOn": "2024-02-10T15:01:12.49766",
  "miles": 6,
  "location": "OUTDOOR"
}

### Create new Run with invalid dates (completedOn is before startedOn)
POST http://localhost:8080/api/runs
Content-Type: RunnerzApplication/json

{
  "id": 10,
  "title": "Saturday Morning Run",
  "startedOn": "2024-02-10T15:00:12.49766",
  "completedOn": "2024-02-10T14:59:12.49766",
  "miles": 6,
  "location": "OUTDOOR"
}

### Update an existing run
PUT http://localhost:8080/api/runs/1
Content-Type: RunnerzApplication/json

{
  "id": 1,
  "title": "Saturday Morning Run",
  "startedOn": "2024-02-10T15:00:12.49766",
  "completedOn": "2024-02-10T15:01:12.49766",
  "miles": 6,
  "location": "INDOOR"
}

### Delete a run
DELETE http://localhost:8080/api/runs/1